// Auto-generated by: npm run db:types
// Run `supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/database.ts`
// to regenerate from your Supabase project.

export type Database = {
  public: {
    Tables: {
      profiles: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      subscriptions: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      scores: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      charities: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      charity_events: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      draws: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      draw_entries: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      winners: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      donations: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      platform_config: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      audit_log: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
    };
    Views: Record<string, never>;
    Functions: Record<string, unknown>;
    Enums: Record<string, unknown>;
  };
};
